DELETE FROM DEPARTMENTS;
INSERT INTO DEPARTMENTS VALUES (DEFAULT, 'Statistics');
INSERT INTO DEPARTMENTS VALUES (DEFAULT, 'Computer Science');
INSERT INTO DEPARTMENTS VALUES (DEFAULT, 'Engineering');
INSERT INTO DEPARTMENTS VALUES (DEFAULT, 'Humanities');


