DELETE FROM TOKEN_TYPES;
INSERT INTO TOKEN_TYPES VALUES (DEFAULT, 'LOGIN', 60, true, false);
INSERT INTO TOKEN_TYPES VALUES (DEFAULT, 'EMAIL_VERIFY', 15, false, true);
INSERT INTO TOKEN_TYPES VALUES (DEFAULT, 'PASSWORD_RESET', 5, false, false);



