DELETE FROM TOPICS;
INSERT INTO TOPICS VALUES (DEFAULT, 'Trading');
INSERT INTO TOPICS VALUES (DEFAULT, 'Transport');
INSERT INTO TOPICS VALUES (DEFAULT, 'Wellbeing');
INSERT INTO TOPICS VALUES (DEFAULT, 'Python');
INSERT INTO TOPICS VALUES (DEFAULT, 'Problem Solving');
INSERT INTO TOPICS VALUES (DEFAULT, 'Public Speaking');
INSERT INTO TOPICS VALUES (DEFAULT, 'Leadership');


